name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: 1.3.4
      - run: bun install --frozen-lockfile
      - run: npm run type
      - run: npm run lint
      - run: bun test

  svg-only-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: 1.3.4
      - run: bun install --frozen-lockfile
      - name: build svg-only action
        run: |
          npm run build:action
          rm -r svg-only/dist
          mv packages/action/dist svg-only/dist
      - name: generate tachikoma svg output
        uses: ./svg-only
        with:
          github_user_name: platane
          outputs: |
            dist/tachikoma.svg
            dist/tachikoma-dark.svg?palette=github-dark
      - name: ensure the generated file exists
        run: |
          test -f dist/tachikoma.svg
          test -f dist/tachikoma-dark.svg

  docker-action-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: generate tachikoma gif output
        uses: ./
        with:
          github_user_name: platane
          outputs: |
            dist/tachikoma.gif
      - name: ensure the generated file exists
        run: test -f dist/tachikoma.gif
